spring:
  datasource:
    url: jdbc:mysql://uproad-1.c3zbqtbixzbk.ap-northeast-2.rds.amazonaws.com:3306/uproad
    username: admin
    password: comet2059!
    hikari:
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      format_sql: true
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: com.halfjang.food.mapapi.common.config.NamingStrategy
  jpa:
    show-sql: true
    hibernate:
#      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
jwt:
  header: Authorization
  secret: UPROADSECURITYKEY
  token-validity-in-seconds: 3600
server:
  port: 8080 # set port to 5000 for serve on AWS
logging:
  file:
    name: log/uproad.log
    max-size: 10MB
    max-history: 1000
  level:
    org.springframework.data: debug
#    kr.co.accurasoft.kcs: DEBUG
#    kr.co.accurasoft.mes.gsg: DEBUG
debug: true
