spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uproad?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: comet1
    hikari:
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080 # set port to 5000 for serve on AWS
logging:
  file:
    name: log/uproad.log
    max-size: 10MB
    max-history: 1000
